export const buyerRequirements = [
  {
    id: 1,
    buyer: "Fresh Harvest Ltd.",
    crop: "Tomato",
    variety: "Hybrid",
    quantity: "5 tons",
    price: "₹20-22/kg",
    location: "Delhi NCR",
    deadline: "Oct 25, 2023",
    verified: true,
    rating: 4.8,
    image: "/placeholder.svg?height=160&width=240",
  },
  {
    id: 2,
    buyer: "Organic Foods Co.",
    crop: "Potato",
    variety: "Kufri Jyoti",
    quantity: "10 tons",
    price: "₹15-16/kg",
    location: "Sonipat",
    deadline: "Oct 30, 2023",
    verified: true,
    rating: 4.5,
    image: "/placeholder.svg?height=160&width=240",
  },
  {
    id: 3,
    buyer: "Green Valley Exports",
    crop: "Onion",
    variety: "Red",
    quantity: "8 tons",
    price: "₹25-28/kg",
    location: "Ghaziabad",
    deadline: "Nov 5, 2023",
    verified: true,
    rating: 4.7,
    image: "/placeholder.svg?height=160&width=240",
  },
];
