export const products = [
    {
      id: 1,
      name: "NPK 19-19-19 Fertilizer",
      category: "Fertilizer",
      brand: "Coromandel",
      price: 1250,
      unit: "50 kg bag",
      rating: 4.7,
      reviews: 128,
      image: "/placeholder.svg?height=192&width=256",
      inStock: true,
      discount: 5,
      verified: true,
      description:
        "A balanced NPK fertilizer suitable for most crops. Provides essential nutrients for plant growth and development.",
      ingredients:
        "Nitrogen 19%, Phosphorus 19%, Potassium 19%, Other nutrients and fillers 43%",
      manufacturingDate: "2023-01-15",
      expiryDate: "2025-01-15",
      location: "Delhi NCR",
    },
    {
      id: 2,
      name: "Tata Rallis Tafgor",
      category: "Insecticide",
      brand: "Tata Rallis",
      price: 450,
      unit: "1 liter",
      rating: 4.5,
      reviews: 96,
      image: "/placeholder.svg?height=192&width=256",
      inStock: true,
      discount: 0,
      verified: true,
      description:
        "Effective insecticide for controlling a wide range of pests in various crops.",
      ingredients: "Dimethoate 30% EC, Emulsifiers and Solvents 70%",
      manufacturingDate: "2023-02-10",
      expiryDate: "2025-02-10",
      location: "Ghaziabad",
    },
    {
      id: 3,
      name: "Hybrid Tomato Seeds",
      category: "Seeds",
      brand: "Syngenta",
      price: 850,
      unit: "500g packet",
      rating: 4.8,
      reviews: 75,
      image: "/placeholder.svg?height=192&width=256",
      inStock: true,
      discount: 10,
      verified: true,
      description:
        "High-yielding hybrid tomato seeds with excellent disease resistance and fruit quality.",
      ingredients: "100% Hybrid Tomato Seeds (Solanum lycopersicum)",
      manufacturingDate: "2023-03-05",
      expiryDate: "2024-03-05",
      location: "Sonipat",
    },
    {
      id: 4,
      name: "Drip Irrigation Kit",
      category: "Equipment",
      brand: "Netafim",
      price: 5500,
      unit: "1 acre kit",
      rating: 4.6,
      reviews: 42,
      image: "/placeholder.svg?height=192&width=256",
      inStock: false,
      discount: 0,
      verified: true,
      description:
        "Complete drip irrigation kit for 1 acre of land. Includes pipes, drippers, filters, and connectors.",
      ingredients:
        "HDPE Pipes, Plastic Drippers, Metal Filters, Plastic Connectors",
      manufacturingDate: "2023-01-20",
      expiryDate: "2028-01-20",
      location: "Delhi NCR",
    },
  ];
  